# CustomMapDownloader/core/constants.py
# -*- coding: utf-8 -*-

"""Constants for CustomMapDownloader core package."""

# GSD:
GSD_MIN = 0.1
GSD_STEP = 0.1
GSD_DECIMALS = 1
GSD_MAX = 1000.0

# CRS / projection policy:
DEFAULT_METRIC_RENDER_CRS_AUTHID = "EPSG:3857"

# Tile / rendering policy:
DEFAULT_MAX_TILE_PX = 2048
MIN_TILE_PX = 64
MAX_TILE_PX = 8192
TILE_RENDER_MAX_RETRIES = 3
TILE_RENDER_BASE_BACKOFF_S = 0.7
TILE_RENDER_MAX_BACKOFF_S = 8.0

# Large raster policy:
LARGE_RASTER_WARN_MAX_DIM_PX = 20_000
LARGE_RASTER_STRONG_MAX_DIM_PX = 40_000
LARGE_RASTER_WARN_TOTAL_PX = 400_000_000
LARGE_RASTER_STRONG_TOTAL_PX = 1_600_000_000
LARGE_EXPORT_WARN_RAW_BYTES = 800 * 1024 * 1024

# GDAL output policy:
GTIFF_CREATE_OPTIONS = ("COMPRESS=LZW", "TILED=YES", "BIGTIFF=IF_SAFER")
JPEG_CREATE_OPTIONS = ("QUALITY=90",)
